# Generated by Django 5.0.6 on 2024-06-14 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100, unique=True)),
                ('BudgetLimit', models.IntegerField()),
                ('ParentID', models.IntegerField()),
                ('CategoryType', models.CharField(choices=[('expense', 'Expense'), ('budget', 'Budget'), ('both', 'Both')], default='expense', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('BudgetID', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('TimeInMonths', models.IntegerField()),
                ('Maximum', models.IntegerField(default=0)),
                ('CategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('CategoryID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.categories')),
            ],
        ),
    ]
